# services:
#   music_compose_backend:
#     image: ${DOCKER_REGISTRY-}musiccomposebackend
#     build:
#       context: .
#       dockerfile: music_compose_backend/Dockerfile

services:
  music_compose_backend:
    container_name: music-compose-api
    build:
      context: .
      dockerfile: music_compose_backend/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: always